stages:
  data_ingestion:
    cmd: python src/A_data_injestion.py
    deps:
    - src/A_data_injestion.py
    - data/src/palmer_penguins.csv
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/B_preperation.py
    deps:
    - data/raw
    - src/B_preperation.py
    outs:
    - data/interim

  feature_Selection:
    cmd: python src/C_feature_selection.py
    deps:
    - data/interim
    - src/C_feature_selection.py
    outs:
    - data/processed
    
  model_building:
    cmd: python src/D_model_training.py
    deps:
    - data/processed
    - src/D_model_training.py
    params:
    - model_building.model_types
    outs:
    - data/models/model.pkl
  model_evaluation:
    cmd: python src/E_model_evaluation.py
    deps:
    - data/models/model.pkl
    - src/E_model_evaluation.py
    metrics:
    - data/reports/metrics.json
